// Generated by gencpp from file fido_pkg/BallPixel.msg
// DO NOT EDIT!


#ifndef FIDO_PKG_MESSAGE_BALLPIXEL_H
#define FIDO_PKG_MESSAGE_BALLPIXEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fido_pkg
{
template <class ContainerAllocator>
struct BallPixel_
{
  typedef BallPixel_<ContainerAllocator> Type;

  BallPixel_()
    : x(0)
    , y(0)  {
    }
  BallPixel_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
    }



   typedef int16_t _x_type;
  _x_type x;

   typedef int16_t _y_type;
  _y_type y;




  typedef boost::shared_ptr< ::fido_pkg::BallPixel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fido_pkg::BallPixel_<ContainerAllocator> const> ConstPtr;

}; // struct BallPixel_

typedef ::fido_pkg::BallPixel_<std::allocator<void> > BallPixel;

typedef boost::shared_ptr< ::fido_pkg::BallPixel > BallPixelPtr;
typedef boost::shared_ptr< ::fido_pkg::BallPixel const> BallPixelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fido_pkg::BallPixel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fido_pkg::BallPixel_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fido_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'fido_pkg': ['/home/turtlebot/catkin_ws/src/fido_pkg/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fido_pkg::BallPixel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fido_pkg::BallPixel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fido_pkg::BallPixel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fido_pkg::BallPixel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fido_pkg::BallPixel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fido_pkg::BallPixel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fido_pkg::BallPixel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d78a6b8c9650c754bf0432d3d1707c3";
  }

  static const char* value(const ::fido_pkg::BallPixel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d78a6b8c9650c75ULL;
  static const uint64_t static_value2 = 0x4bf0432d3d1707c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::fido_pkg::BallPixel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fido_pkg/BallPixel";
  }

  static const char* value(const ::fido_pkg::BallPixel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fido_pkg::BallPixel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 x\n\
int16 y\n\
";
  }

  static const char* value(const ::fido_pkg::BallPixel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fido_pkg::BallPixel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct BallPixel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fido_pkg::BallPixel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fido_pkg::BallPixel_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIDO_PKG_MESSAGE_BALLPIXEL_H
